### ISSUE TITLE
Generating secret name with hash

### ISSUE THREAD

**Issue by iatzmon** [viaduct-ai/kustomize-sops#10]
Hi,
I'm trying to use the plugin in my local environment and I'm able to encode my secrets but the name of the generated secret doesn't include a hash. I tried to add the `kustomize.config.k8s.io/needs-hash: "true"` annotation to the secret definition, but it seems this annotation is only supported in Kustomize v3.2.2 and onwards. 
Should I try to compile the plugin using v3.2.2 or is there a better way to achieve this?
I tried to update the version in the go.mod file to 3.2.2 but when I run install_kustomize.sh I get this error: `go: sigs.k8s.io/kustomize/v3@v3.2.2: reading sigs.k8s.io/kustomize/go.mod at revision v3.2.2: unknown revision v3.2.2`

Thanks

**Comment by devstein** [comment]
Hi @iatzmon 

Unfortunately, `kustomize` restructured their Go packages after the `v3.2.0` release, so `v3.2.0` is the latest version of sigs.k8s.io/kustomize/v3 go package. I’m going to update `ksops` to use the new version of kustomize Go API `sigs.k8s.io/kustomize/api` this week and update the installation script accordingly.

However, in the meantime can you try running the following **outside your $GOPATH**

```bash
# remove existing kustomize binary 
rm $(command -v kustomize)

# https://github.com/kubernetes-sigs/kustomize/blob/master/docs/INSTALL.md#try-go
GO111MODULE=on go install sigs.k8s.io/kustomize/kustomize/v3 

# check the latest kustomize was install properly
kustomize version

# Now go back to ksops directory 
cd $GOPATH/src/github.com/viaduct-ai/kustomize-sops

#  Install ksops 
./scripts/build-and-install-ksops.sh
```

Let me know if this works!  And thanks for making an issue 😄

**Comment by iatzmon** [comment]
Hi @devstein,

Thanks for the quick response!
I tried to follow your instructions but they don't seem to work for me.
I'm not sure which version of kustomize is getting installed since when I run `kustomize version` I'm getting
`{Version:unknown GitCommit:$Format:%H$ BuildDate:1970-01-01T00:00:00Z GoOs:darwin GoArch:amd64}`
and after I rebuild ksops and try to run `kustomize build --enable_alpha_plugins` on my application I'm getting a `plugin was built with a different version of package golang.org/x/sys/unix` error

**Comment by devstein** [comment]
@iatzmon Do you mind checking out my branch `devstein/kustomize/api/v0.3.1` and try re-running the `install-kustomize.sh`, then `build-and-install-ksops.sh` and then seeing if it works? This should update you to the latest `kustomize`

**Comment by iatzmon** [comment]
@devstein I had to change the value `TEST_PLUGIN_PATH` in `build-and-install-ksops.sh` since it is hardcoded to your system and after that I managed to compile `kustomize` and the plugin. The strange thing is that the `kustomize.config.k8s.io/needs-hash: "true"` annotation is still being ignored during the build. How can I verify that I'm using the latest kustomize? `kustomize version` still returns `{Version:unknown GitCommit:$Format:%H$ BuildDate:1970-01-01T00:00:00Z GoOs:darwin GoArch:amd64}`

**Comment by devstein** [comment]
@iatzmon Fixed the hardcode path (sorry about that)! The `version` command of the Go installation is broken but you are guaranteed to be on the latest ([see the docs](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/INSTALL.md)) as long as there isn't another kustomize installation in your $PATH.

Would you mind commenting an example of what you are trying to do and I can debug locally (and add a test for future users 😃 )?

**Comment by devstein** [comment]
@iatzmon Can you verify that this annotation functionality works with Go plugins, on a closer look at the [kustomize docs](https://github.com/kubernetes-sigs/kustomize/blob/644f2ddcdc3123b285f86e3e1d288b540042e4a1/docs/plugins/README.md#generator-options) it only mentions setting annotations for **exec plugins**

**Comment by devstein** [comment]
I'll try implementing this natively in this plugin in the future!

**Comment by davinkevin** [comment]
I'm also waiting for this one ❤️

**Comment by devstein** [comment]
@davinkevin Noted! I've been hoping Kustomize would enable this functionality natively for Go plugins, but I'll see if prioritize in the coming weeks 😄
