### ISSUE TITLE
Create new release based on SOPS 3.7.0

### ISSUE THREAD

**Issue by polarctos** [viaduct-ai/kustomize-sops#100]
SOPS was released in version 3.7.0.

The dependency was also already updated in `kustomize-sops` here: https://github.com/viaduct-ai/kustomize-sops/pull/98

Would it be possible to release a new version here?

One of the new features in SOPS 3.7.0 is `age` support, see [sops changelog](https://github.com/mozilla/sops/blob/v3.7.0/CHANGELOG.rst).

**Comment by devstein** [comment]
@polarctos Done! Version `v2.5.1` will be released shortly

**Comment by polarctos** [comment]
Thanks a lot! 👏
