### ISSUE TITLE
typo error caused failure when using kops with argocd

### ISSUE THREAD

**Issue by majinghe** [viaduct-ai/kustomize-sops#104]
When try to enable kustomize plugins via Argo CD ConfigMap, if the data is 

``` 
kustomize.buildOptions: "--enable-alpha-plugins"
```
argocd  will show error 
```
Unable to create application: application spec is invalid: InvalidSpecError: Unable to get app details: rpc error: code = Unknown desc = `kustomize build /tmp/https:__github.ibm.com_crmk8sdevops_devops4newco/helm-charts/kustomize/apim/overlays/svt --enable-alpha-plugins` failed exit status 1: Error: unknown flag: --enable-alpha-plugins
```
If change the "-" to "_", then the error  will fixed, that means configmap data should be like this
```
 kustomize.buildOptions: "--enable_alpha_plugins"
```

Argocd image is `quay.io/argoproj/argocd:v2.0.0`.

**Comment by devstein** [comment]
Hi @majinghe thanks for making an issue! The error you are seeing is associate with a breaking change in the `kustomize` `v4` API and the corresponding version `v2.5.0` in KSOPS. `kustomize` switched all flags to be dash-separated to be compatible with `kubectl`. 

What version of `kustomize` and KSOPS are you using in Argo CD? You can find it by running `kustomize version` from within the Argo CD deployment.

**Comment by majinghe** [comment]
Hi @devstein  i used kops with argocd for a long time, i used latest argocd(v2.x) yesterday,  the kustomize version is 
```
$ kustomize version
{Version:kustomize/v3.9.4 GitCommit:e41d94ddef8cca7af2709c4104b41c4d43cd236c BuildDate:2021-02-09T19:22:10Z GoOs:linux GoArch:amd64}
```

**Comment by devstein** [comment]
> Does this need to do some comment on the docs? I think this is helpful. kops is very excellent for GitOps.

Goo idea @majinghe , this could be helpful to future users as well. Can you update [your PR](https://github.com/viaduct-ai/kustomize-sops/pull/105/files) to add this comment? Something like:

```yaml
data:
  # For KSOPs versions < v2.5.0, use the old kustomize flag style
  # kustomize.buildOptions: "--enable_alpha_plugins"
  kustomize.buildOptions: "--enable-alpha-plugins"
```
