### ISSUE TITLE
Deprecate Go plugin?

### ISSUE THREAD

**Issue by daurnimator** [viaduct-ai/kustomize-sops#110]
#54 has been quite successful for us.

I think would be a good idea to encourage all users to use that form, and deprecate the library form.
That would reduce the maintenance burden and frequent releases required to keep up with kustomize.

**Comment by devstein** [comment]
@daurnimator Fair point. Let me investigate and will let you know.

**Comment by daurnimator** [comment]
Any further thoughts?

**Comment by devstein** [comment]
Hi @daurnimator thanks for following up. Yes, after thinking it through I'm going to deprecate the Go plugin in the next major release. I don't have a timeline for the release, but will tag you in the PR

**Comment by devstein** [comment]
@daurnimator please review https://github.com/viaduct-ai/kustomize-sops/pull/127
