### ISSUE TITLE
is ksops v2.5.5 compitable with ArgoCD 2.0.1

### ISSUE THREAD

**Issue by veerendra2** [viaduct-ai/kustomize-sops#111]
From [this](https://github.com/viaduct-ai/kustomize-sops#ksops-repo-sever-patch) section's code snippet. There is a comment `# Match Argo CD Go version`, but not in anywhere in docs that Golang has to match (Or did I miss?)

But I see
* ksops v2.5.5's Golang version is v1.14
* ArgoCD v2.0.1's Golang version is v1.16(From [here](https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/upgrading/1.8-2.0.md))

I wonder, is ksops v2.5.5 compitable with ArgoCD 2.0.1?

**Comment by devstein** [comment]
@veerendra2 Thanks for making an issue and great question! I confirmed that KSOPS v2.5.5 works with ArgoCD 2.0.1

I'll remove the comment to avoid further confusion.
