### ISSUE TITLE
ArgoCD Setup - Private Key Use?

### ISSUE THREAD

**Issue by jhoover4** [viaduct-ai/kustomize-sops#115]
Hello!

I've followed the documentation for ArgoCD to install the integration, but I'm a little lost on how KSOPS retrieves the private key to decrypt with Argo. Is there a Secret I need to apply that I'm missing?

**Comment by devstein** [comment]
Hi @jhoover4 , thanks for making an issue!

Are you using manually managed PGP keys or a key management service like AWS KMS?

If you are using manually managed PGP keys, this [previous issue](https://github.com/viaduct-ai/kustomize-sops/issues/24#issuecomment-623784329) might help you out

**Comment by jhoover4** [comment]
We're using Vault to manage our keys. I actually did see that issue and examples, but the manual key process seems a bit complicated :/

Any chance there's some way to pull the keys from vault?

**Comment by devstein** [comment]
Have you looked at the [SOPS + Vault documenation](https://github.com/mozilla/sops#encrypting-using-hashicorp-vault)? It shows a way of accessing and authenticating to Vault remotely. To integrate with Argo CD, you would just need to make sure it has the necessary dependencies (`vault`) to authenticate with Vault to fetch the keys

**Comment by jhoover4** [comment]
Awesome! This looks promising. Would these commands go in the initContainer or somewhere else? (Forgive me K8s newbness)

**Comment by devstein** [comment]
> Would these commands go in the initContainer or somewhere else? 

You would use an `initContainer` to install `vault`  and `KSOPS` in Argo CD. Check out the [Argo CD custom tooling docs](https://argoproj.github.io/argo-cd/operator-manual/custom_tools/)

With `vault` and `KSOPS` installed and the necessary Vault credentials (token) configure, Argo CD should be able to automatically decrypt the secrets

**Comment by devstein** [comment]
@jhoover4 Closing this issue, but let me know if you have any more questions!
