### ISSUE TITLE
build works with ksops-exec but not ksops

### ISSUE THREAD

**Issue by jmclean-starburst** [viaduct-ai/kustomize-sops#117]
KSOPS version: 2.5.5

Issue:
when I run `kustomize build --enable-alpha-plugins .` on a directory that leverages KSOPS, I receive the below (stack trace omitted)
```
kustomize build --enable-alpha-plugins .
2021/06/01 08:27:03 Attempting plugin load from '/Users/me/.config/kustomize/plugin/viaduct.ai/v1/ksops/ksops.so'
fatal error: runtime: no plugin module data
```

Its interesting that if i change the `kind` of my generator manifest to `ksops-exec`, kustomize is able to build and spits out a perfect looking template

I cannot pivot to `ksops-exec` because I leverage the KSOPS plugin in ArgoCD as a custom image, which the `viaductoss/ksops:2.5.5` does not have the ksops-exec binary within it. 

Any assistance would be appreciated!

**Comment by devstein** [comment]
Hi, @jmclean-starburst thanks for making an issue! Would you mind sharing the output of

```bash
ls -la /Users/me/.config/kustomize/plugin/viaduct.ai/v1/ksops/
```


---


For integrating the `ksops-exec` plugin with an Argo CD custom image, the `ksops-exec` binaries are published with every release, so you can use `wget` to download the binary and make it available in the ArgoCD image

**Comment by jmclean-starburst** [comment]
> Hi, @jmclean-starburst thanks for making an issue! Would you mind sharing the output of
> 
> ```shell
> ls -la /Users/me/.config/kustomize/plugin/viaduct.ai/v1/ksops/
> ```
> 
> For integrating the `ksops-exec` plugin with an Argo CD custom image, the `ksops-exec` binaries are published with every release, so you can use `wget` to download the binary and make it available in the ArgoCD image

```
> ls -lart ~/.config/kustomize/plugin/viaduct.ai/v1/ksops
total 69728
drwxr-xr-x  3 me  staff    96B Jun  1 10:17 ./
-rw-r--r--  1 me  staff    34M Jun  1 10:17 ksops.so
drwxr-xr-x  4 me  staff   128B Jun  1 10:17 ../
```

**Comment by devstein** [comment]
The folder structure looks good, so it's an issue with the binary itself.  Can you rebuild `kustomize` and `KSOPS` and try re-build the manifests? 

```bash
# From the root of this repo
make kustomize
make install
kustomize build --enable-alpha-plugins .
```

---

If you still encounter the same error, can you share the following outputs

1. `kustomize version`
2. `go env`

**Comment by jmclean-starburst** [comment]
1. `make kustomize`
This failed w/ the below
```
./scripts/install-kustomize.sh
WARNING: Found an existing installation of kustomize at /usr/local/bin/kustomize
Please confirm you want to reinstall kustomize (y/n): y
Removing existing kustomize executable...
rm /usr/local/bin/kustomize
Installing kustomize...
Successfully installed kustomize!
./scripts/install-kustomize.sh: line 22: kustomize: command not found
make: *** [kustomize] Error 127
```
> bc of this failure, I had to  `brew uninstall kustomize; brew install kustomize`

2. `make install`
```
go install
rm "ksops.so" || true
rm "ksops" || true
rm -rf /Users/alpha-wolf/.config/kustomize/plugin/viaduct.ai/v1/ || true
rm -rf /Users/alpha-wolf/sigs.k8s.io/kustomize/plugin/viaduct.ai/v1/ || true
go build -o "ksops"
go build -buildmode plugin -o "ksops.so"
./scripts/install-ksops.sh
./scripts/install-ksops.sh: line 29: [: ==: unary operator expected
Copying plugin to the kustomize plugin path...
cp ksops.so /Users/alpha-wolf/.config/kustomize/plugin/viaduct.ai/v1/ksops/
Copying plugin to the test kustomize plugin path...
cp ksops.so /Users/alpha-wolf/sigs.k8s.io/kustomize/plugin/viaduct.ai/v1/ksops/
Copying exec plugin to the kustomize plugin path...
cp ksops /Users/alpha-wolf/.config/kustomize/plugin/viaduct.ai/v1/ksops-exec/ksops-exec
Copying exec plugin to the test kustomize plugin path...
cp ksops /Users/alpha-wolf/sigs.k8s.io/kustomize/plugin/viaduct.ai/v1/ksops-exec/ksops-exec
```
3. `kustomize build --enable-alpha-plugins .`
* Yielded same issue as original post.

Kustomize Version: 4.1.3
Go Version: 1.15.6

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/alpha-wolf/Library/Caches/go-build"
GOENV="/Users/alpha-wolf/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/alpha-wolf/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/alpha-wolf/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.15.6/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.6/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/pr/wrsgr_fd57bcnht422blbwq40000gn/T/go-build808802244=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

> Note: I was changing my user from `alpha-wolf` to `me` in posts above, but too much replacement for debugging purposes.

**Comment by devstein** [comment]
Thanks @jmclean-starburst! The source of the issue is from step `1.` 

>bc of this failure, I had to brew uninstall kustomize; brew install kustomize

The installation error 

```bash
Successfully installed kustomize!
./scripts/install-kustomize.sh: line 22: kustomize: command not found
```

indicates that the `kustomize` binary installed via Go is not within your `PATH`. See instructions for fixing [here](https://golang.org/doc/gopath_code#GOPATH).

In order to use `kustomize` Go plugins, you need to install `kustomize` via Go. That is why `kustomize` if failing to load the plugin and returning `fatal error: runtime: no plugin module data`. Let me know if this makes sense and if you are able to resolve!

---

This also raises the larger question of https://github.com/viaduct-ai/kustomize-sops/issues/110 and whether or not it is worth maintaining the Go plugin when there is all of this additional complexity

**Comment by jmclean-starburst** [comment]
thank you for the response. your google abilities are superior to mine ;)
