### ISSUE TITLE
M1 Build 

### ISSUE THREAD

**Issue by imranismail** [viaduct-ai/kustomize-sops#122]

**Comment by devstein** [comment]
Ho @imranismail can you please provide more details?

**Comment by imranismail** [comment]
Hey apologies,

In my organization, there's one of our devs that uses the new M1 Mac with arm architecture. It'd be great if sops has a build for darwin and arm architecture.

**Comment by devstein** [comment]
Thanks for the context @imranismail! This should be fixed in the next release
