### ISSUE TITLE
How to encrypt (non JSON/YAML) files as secrets?

### ISSUE THREAD

**Issue by cameronkerrnz** [viaduct-ai/kustomize-sops#125]
I'm new to KSOPS and Kustomize. I'm wanting to use Kustomize and KSOPS to encrypt a type (in this case a Python file that contains secrets for a Django application, but it could similarly be something like a wallet or a licence file.)

I know SOPS itself can do this, because I can do a 'sops -e secrets.py' and a subsequent 'sops -d' on it.
I know that Kustomize could use its secrets_generator functionality to build a Kubernetes Secret from some files.
I see that KSOPS uses a different generator, and see no indication of how (if) a file itself can be encrypted.

Before attempting to use ksops, I had the following in kustomization.yaml, which I'm trying to replicate with ksops:

```yaml
secretGenerator:
- name: django-demo-secrets
  files:
  - secrets/secrets.py
```

Moving to ksops, I replaced the above with the following:

```yaml
generators:
- secret-generator.yaml
```

and in secret-generator.yaml, I have:

```yaml
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: django-demo-secrets
files:
  - secrets/secrets.py
```

secrets/secrets.py is a SOPS-encrypted file using GPG and ksops can decrypt it (bypassing kustomize build for the moment)

```
/root/.config/kustomize/plugin/viaduct.ai/v1/ksops/ksops secret-generator.yaml 

SECRET_KEY = 'DEMO-SUPER-SECRET=DEMO-SUPER-SECRET=DEMO-SUPER-SECRET=DEMO-SUPER-SECRET'
...
--- <--- seems it added YAML document separator
```

But kustomize is giving me an error:

```
# kustomize build --enable-alpha-plugins .
Error: yaml: line 11: mapping values are not allowed in this context
```

Seems that kustomize is expecting the output to be YAML. I see that what I'm supposed to encrypt is meant to be a Secret, but what I really want to do is to encrypt the content of a secret generator. Is that possible?

I'd prefer not to have a create a Secret such as the following, because embedding files in YAML is ... well unsustainable and prone to numerous kinds of errors. Being able to use this as I would a secretGenerator also has the advantage of including the hash in the name.

Thanks,
Cameron

**Comment by devstein** [comment]
Hi @cameronkerrnz thanks for making an issue! Unfortunately, the scenario you are describing is not possible with KSOPS.  KSOPS design is intentionally simple and only works with encrypted kubernetes resources. KSOPS doesn't generate the Kubernetes resource for you like the `secretGenerator`. 

If you want to avoid embedding the Python file in a YAML, I recommend checking out alternative [kustomize + SOPS plugins](https://github.com/goabout/kustomize-sopssecretgenerator) that are designed to support this use-case.
