### ISSUE TITLE
How to control SOPS plugin version?

### ISSUE THREAD

**Issue by FelixRodriguezJara** [viaduct-ai/kustomize-sops#13]
Hello,

We are using ksops integration with ArgoCD and it works very well. Due to problems we found while deploying secrets based on different SOPS versions (we were encrypting with 3.5.0 and the plugin uses 3.4.0), now, we are looking at how to control the version of SOPS the plugin uses. Could you please guide me on how to achieve this?

Thank you very much.

Kind regards.

**Comment by devstein** [comment]
Hi @FelixRodriguezJara 

Are you able to decrypt secrets with `3.5.0` that were encrypted with `3.4.0` ? If so, this https://github.com/viaduct-ai/kustomize-sops/pull/12 that I will merge today will fix this issue for you because it upgrades the SOPS Go module. 

If not, I can consider adding SOPS version functionality in the generator resource, an optional `sops_version: 3.4.0`  parameter, but ideally we can always keep KSOPS update with latest SOPS and avoid this change.

I'll let you know when I merge and release this change, so you can test it out!

**Comment by devstein** [comment]
@FelixRodriguezJara Try out the new `v2.0.0` release and let me know if this is still an issue! Just update your repo server patch or custom build via https://github.com/viaduct-ai/kustomize-sops#ksops-repo-sever-patch

**Comment by FelixRodriguezJara** [comment]
Thank you very much for your quick reaction, Devin! :)

We will test this as soon as possible and will let you know the result. 

We haven't tried decrypting secrets encrypted with 3.4.0 using sops 3.5.0, but it should work, shouldn't it? 

Having the repo server using the latest version would be okay, anyway, I think that it would be nice to be able to control, with a variable as you mentioned, which version of sops it has been used. This way, version of sops is always known, fixed, and non dependant of the moment you build the image (we have used the Docker file to build our custom image and speed up the startup of the repo server instance). What do you think? 

Thank you very much!

Kind regards.

**Comment by devstein** [comment]
3.4.0 appears to work with SOPS 3.5.0 for me!

I'm hesitant to add additional functionality unless this becomes a re-occurrring issue, but will keep this flagged for the future!

Also, we created a [public KSOPS docker image](https://hub.docker.com/r/viaductoss/ksops) to speed up build times for both the init container and custom build approaches.

**Comment by FelixRodriguezJara** [comment]
Hello Devin,

I have tried using the image you have built instead of mine (I have created a new one using the new version of the dockerfile) and it doesn´t work. It does work with the image I have built though. The initialization error I am getting is the following one:

`Error: failed to start container "argocd-repo-server": Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"uid_entrypoint.sh\": executable file not found in $PATH": unknown`

The yaml file I am using to define repo server deployment is:

`apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    spec:
      containers:
      - name: argocd-repo-server
        command:
        - uid_entrypoint.sh
        - argocd-repo-server
        - --sentinel
        - argocd-redis-ha-announce-0:26379
        - --sentinel
        - argocd-redis-ha-announce-1:26379
        - --sentinel
        - argocd-redis-ha-announce-2:26379
        - --sentinelmaster
        - argocd
        image: viaductoss/ksops
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /usr/local/bin/argocd-flux-plugin
          name: custom-tools
          subPath: argocd-flux-plugin
        - name: gcp-cred-vol
          mountPath: "/gcp-cred"
          readOnly: true
        env:
          - name: XDG_CONFIG_HOME
            value: /.config
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /gcp-cred/gcp-credentials.json
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: custom-tools
        emptyDir: {}
      - name: gcp-cred-vol
        secret:
          secretName: gcp-credentials
      initContainers:
      - name: download-tools
        image: alexmt/argocd-flux:latest
        command: [sh, -c]
        args:
        - cp /usr/local/bin/argocd-flux-plugin /custom-tools/argocd-flux-plugin
        volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools`

Am I doing anything wrong?

Thank you very much.

**Comment by devstein** [comment]
@FelixRodriguezJara Sorry for the confusion, the `ksops` image doesn't have Argo CD installed. It only builds the `ksops` plugin and `kustomize`. So you still need to create your own image or use the init container, which is much faster now that `ksops` and `kustomize` are already built. 

Here is the customer Docker image that builds off the `ksops` image
```Dockerfile
ARG ARGO_CD_VERSION="v1.3.6"
# Always match Argo CD Dockerfile's Go version!
# https://github.com/argoproj/argo-cd/blob/master/Dockerfile
ARG KSOPS_VERSION="v2.0.0"

#--------------------------------------------#
#--------Build KSOPS and Kustomize-----------#
#--------------------------------------------#

FROM viaductoss/ksops:$KSOPS_VERSION as ksops-builder

#--------------------------------------------#
#--------Build Custom Argo Image-------------#
#--------------------------------------------#

FROM argoproj/argocd:$ARGO_CD_VERSION

# Switch to root for the ability to perform install
USER root

# Set the kustomize home directory
ENV XDG_CONFIG_HOME=$HOME/.config
ENV KUSTOMIZE_PLUGIN_PATH=$XDG_CONFIG_HOME/kustomize/plugin/

ARG PKG_NAME=ksops

# Override the default kustomize executable with the Go built version
COPY --from=ksops-builder /go/bin/kustomize /usr/local/bin/kustomize

# Copy the plugin to kustomize plugin path
COPY --from=ksops-builder /go/src/github.com/viaduct-ai/kustomize-sops/*  $KUSTOMIZE_PLUGIN_PATH/viaduct.ai/v1/${PKG_NAME}/

# Switch back to non-root user
USER argocd

```

**Comment by FelixRodriguezJara** [comment]
Alright, thank you very much, Devin, that makes sense. I close the issue then.

Thank you very much!

Kind regards.
