### ISSUE TITLE
Multi-tenant? 

### ISSUE THREAD

**Issue by flickerfly** [viaduct-ai/kustomize-sops#138]
I'd like ArgoCD to be the gateway for multiple users with unique keys to deploy resources onto my cluster. How can I assure one user can't decrypt another user's data with ArgoCD's access? I was looking at maybe KMS context as a solution to force injection of the project into the KMS request, but don't see the full path. Looks like SOPS supports it though.

**Comment by devstein** [comment]
Hi @flickerfly thanks for making an issue. This depends on your setup and the isolation requirements you are looking for. 

If keys are unique to a specific Argo CD applications (no app has multiple keys), then my intuition would be to try something like

1. Use [Argo CD RBAC](https://argoproj.github.io/argo-cd/operator-manual/rbac/) to lock down user view permissions on the app-level
2. Allow Argo CD access to all KMS keys, so if a user has access to the app then they will also be able to see the secret

I don't know if Argo CD custom tools, can get access to the current user information, but if so, you could build a wrapper around your build tools to restrict access based on who the user is 

Hope this helps!
