### ISSUE TITLE
Ksops with ArgoCD - key stored in Azure KV

### ISSUE THREAD

**Issue by avodaqstephan** [viaduct-ai/kustomize-sops#140]
Hi folks, 

I scanned the README and found instruction on how to add AWS keys to the argocd by adding the environment variables `AWS_ACCESS_KEY_ID` & `AWS_SECRET_ACCESS_KEY`. 
By looking at the already closed issues I came across the instruction on how to handle them when GCP is used - [Click](https://github.com/viaduct-ai/kustomize-sops/issues/6).

I couldn't find anything on Azure KV, though. Can you help me out here? 

Many thanks in advance.

Kind regards, 
Stephan

**Comment by szEvEz** [comment]
You could try out the [this](https://github.com/mozilla/sops#encrypting-using-azure-key-vault)
