### ISSUE TITLE
Install script fails on M1 Mac

### ISSUE THREAD

**Issue by jeff-french** [viaduct-ai/kustomize-sops#151]
When following the install instructions in the README on an M1 Mac I get the output:

```shell
curl -s https://raw.githubusercontent.com/viaduct-ai/kustomize-sops/master/scripts/install-ksops-archive.sh | bash
Verify ksops plugin directory exists and is empty
Downloading latest release to ksops plugin path
tar: Error opening archive: Unrecognized archive format
```

This is due to the architecture detection not having support for M1 Macs therefore it doesn't build the correct url to download the Darwin ARM64 build.

This can be fixed by inserting:

```
arm64) machine_arch="arm64" ;;
```

after line 25 of the following function:

https://github.com/viaduct-ai/kustomize-sops/blob/e02d09fa2cd9e9f19f99ea245a2ea07a3adf918e/scripts/install-ksops-archive.sh#L21-L26

**Comment by devstein** [comment]
@jeff-french Thanks for making a quality issue! Feel free to make a PR to fix; otherwise, I'll will later this week.
