### ISSUE TITLE
FYI: Your plugin has been added to Awesome Kustomize list

### ISSUE THREAD

**Issue by aabouzaid** [viaduct-ai/kustomize-sops#160]
Hi :wave: 

I just started an [Awesome Kustomize](https://github.com/aabouzaid/awesome-kustomize/#generators) list :tada:
Because after using Kustomize for 3 years, there was no central place for Kustomize resources.

I find your plugin helpful for real use cases, so add it to the list.

Thank you :rocket:

**Comment by trainoasis** [comment]
Awesome, thanks @aabouzaid !
