### ISSUE TITLE
Add OCI label(s) to docker images

### ISSUE THREAD

**Issue by james-callahan** [viaduct-ai/kustomize-sops#171]
I'd like to take advantage of renovate's changelog support (https://docs.renovatebot.com/modules/datasource/docker/)

To do so, the recommended way is to add the standard OCI label `org.opencontainers.image.source`.
This is useful for all sorts of tools.

A full list of pre-defined annotations is available at: https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys

**Comment by devstein** [comment]
@james-callahan Great idea. Feel free to contribute and make the needed changes to the [`.goreleaser` config](https://github.com/viaduct-ai/kustomize-sops/blob/master/.goreleaser.yml#L63-L69); otherwise, I can tackle once I have bandwidth

**Comment by james-callahan** [comment]
> make the needed changes to the [`.goreleaser` config](https://github.com/viaduct-ai/kustomize-sops/blob/master/.goreleaser.yml#L63-L69)

Any reason to put it in the `.goreleaser` config rather than the Dockerfile?

**Comment by devstein** [comment]
> Any reason to put it in the .goreleaser config rather than the Dockerfile?

@james-callahan For this specific label, no. For labels that change between releases, `.goreleaser` makes templating easy. 

Feel free to add directly to the docker image.

**Comment by james-callahan** [comment]
This regressed via https://github.com/viaduct-ai/kustomize-sops/pull/180/files#r1195838548
