### ISSUE TITLE
Docker images are large

### ISSUE THREAD

**Issue by james-callahan** [viaduct-ai/kustomize-sops#175]
The official ksops docker images are quite large.
They seem to contain the entire `GOPATH` including full source code for all dependencies (now totaling 1.8GB!).

I'd suggest creating a multi-stage dockerfile with minimal things present in the final image.

**Comment by trandersen-ufst** [comment]
2.9 GB on disk here in Docker Desktop.

**Comment by devstein** [comment]
@james-callahan Thanks for flagging! This is not intended 😅 

Feel free to make a PR to fix; otherwise, I'll fix in the next week

**Comment by trandersen-ufst** [comment]
170 Mb on disk in Docker Desktop here.   Very nice, thank you :)
