### ISSUE TITLE
Instructions on  how to make "kubectl apply -k" function with ksops?

### ISSUE THREAD

**Issue by trandersen-ufst** [viaduct-ai/kustomize-sops#177]
I was wondering if it is possible to integrate ksops in the kustomize embedded in modern kubectl binaries.  Right now we use the docker image to apply the ksops kustomize to our yaml files, but it would be much simpler to just have "kubectl apply -k ..." work.

To my understanding this currently requires passing `--enable-alpha-plugins --enable-exec` to kustomize which I am not familiiar enough with kubectl to see how to provide.   Is this possible at the moment or near future, and if yes, how?

**Comment by devstein** [comment]
Thanks for making an issue @trandersen-ufst. To my knowledge, you cannot use kustomize plugins the the `kubectl apply -k` command. The typical usage pattern is to install KSOPS locally and run

```bsah
 kustomize build  --enable-alpha-plugins --enable-exec . | kubectl apply -f -
```

**Comment by trandersen-ufst** [comment]
Thank you.  This is what we do as well with the docker image.  I was just wondering if we could simplify it a bit, but apparently not yet.
