### ISSUE TITLE
Is ksop.so file still needed?

### ISSUE THREAD

**Issue by AnthonyWC** [viaduct-ai/kustomize-sops#192]
From local testing kustomize build would error out if this file wasn't found in `$KUSTOMIZE_PLUGIN_HOME/viaduct.ai/v1/ksops` but in viaductoss/ksops:v4.2.1 this file doesn't exists.  Is this file still needed?

**Comment by devstein** [comment]
Hey @AnthonyWC thanks for making an issue! No `ksops.so` is no longer needed. The output binary is `ksops` (no suffix), which should be compatible with the old legacy exec style plugin (fka `ksops.so`) and new KRM style plugin standard.

Hope this helps and let me know if you have follow up questions!

**Comment by yuriididuk89** [comment]
Hi. Got this error ```Error: loading generator plugins: failed to load generator: expected file with Go object code at: /Users/paragon/.config/kustomize/plugin/viaduct.ai/v1/ksops/ksops.so
error: no objects passed to apply```  on mac air m1. kustomize, sops, ksops installed via brew. Pls help resolve this.

**Comment by devstein** [comment]
Hi @yuriididuk89 can you share the command you ran to get this error?

Also, see #195 if you are having issues installing on an M!

**Comment by yuriididuk89** [comment]
Thanks for your feedback.`(kustomize build --enable-alpha-plugins kustomize/kitweb/stg/apps/ | kubectl apply -f -)` But after a few hours of struggling with this error I finally solved it. Here is my solution and maybe it will help someone. In my case this command source <(curl -s https://raw.githubusercontent.com/viaduct-ai/kustomize-sops/master/scripts/install-ksops-archive.sh) did not work. So I downloaded the content from the script and created a script myself that I ran as sudo.  Then `mv /usr/local/bin/ksops /Users/paragon/.config/kustomize/plugin/viaduct.ai/v1/ksops/ ` and and everything worked. I also tested the following solution -- when I moved the binary file installed via brew into `.config/kustomize/plugin/viaduct.ai/v1/ksops/` -- it didn't work And when I installed it from the script, everything worked fine and + ksops work without these variables `export XDG_CONFIG_HOME=$HOME/.config
export KUSTOMIZE_PLUGIN_HOME=$XDG_CONFIG_HOME/kustomize/plugin/`.

**Comment by devstein** [comment]
@yuriididuk89 Sorry for all the issues, but glad to hear you fixed it. I'll prioritize #195 as soon as I can
