### ISSUE TITLE
Update SOPS

### ISSUE THREAD

**Issue by nbjohnson** [viaduct-ai/kustomize-sops#200]
Now that SOPS has moved from Mozilla to CNCF, a new updated version has been recently released, can ksops be updated to use the new up-to-date release

https://github.com/getsops/sops/releases/tag/v3.8.0

**Comment by devstein** [comment]
@nbjohnson You beat me to this :) I was about to create this issue. Yes we should definitely update

**Comment by devstein** [comment]
Fixed in [v4.2.2](https://github.com/viaduct-ai/kustomize-sops/releases/tag/v4.2.2)
