### ISSUE TITLE
Example failing with GCP KMS

### ISSUE THREAD

**Issue by streetmapp** [viaduct-ai/kustomize-sops#22]
I've gone through the example on the README and in trying the final step of `kustomize build --enable_alpha_plugins .`, I get the following error:

`Error: trouble decrypting file ./secret.enc.yaml: No keys found in file`

Any thoughts on what could be going on?

**Comment by devstein** [comment]
Hi @streetmapp thanks for making an issue! That error could be one of two issues:

1. You didn't import the PGP keys before running `sops -e secret.yaml > secret.enc.yaml`. If so, you should run `gpg --import ./test/key.asc`, then re-follow the README.
2. You didn't add your `gcp_kms` key to the `.sops.yaml` file before running `sops -e secret.yaml > secret.enc.yaml`. See the [SOPS README](https://github.com/mozilla/sops#using-sops-yaml-conf-to-select-kms-pgp-for-new-files) for instructions. 

Let me know if either of these solutions works 👍

**Comment by streetmapp** [comment]
So I guess it can be chalked up to number 2, but that's pretty bizarre. Mainly because I did get an encrypted file when i ran `sops -e secret.yaml > secret.enc.yaml`. But did notice that yesterday when I did this, the `gcp_kms` key had no value compared to when I just ran it now.
