### ISSUE TITLE
Using PGP w/ ArgoCD

### ISSUE THREAD

**Issue by HumairAK** [viaduct-ai/kustomize-sops#24]
Trying to use PGP decryption, similar to how it's described in the README.md for local kustomize builds, but with ArgoCD, and I'm encountering a few issues - hoping to get some clarification. I'm using a custom repo-server (much like the one found [here](https://argoproj.github.io/argo-cd/operator-manual/custom_tools/) at the bottom), this is the one: 

```
      FROM argoproj/argocd:latest
      # Switch to root for the ability to perform install
      USER root
      # Install tools needed for your repo-server to retrieve & decrypt secrets, render manifests
      # (e.g. curl, awscli, gpg, sops)
      RUN apt-get update && \
          apt-get install -y \
              curl \
              awscli \
              rsync \
              gpg && \
          apt-get clean && \
          rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
          curl -o /usr/local/bin/sops -L https://github.com/mozilla/sops/releases/download/v3.5.0/sops-v3.5.0.linux && \
          chmod +x /usr/local/bin/sops
      # Switch back to non-root user
      USER argocd
```
And I'm patching ksops onto the reposerver using the patch from the README. 
I manually add the gpg private keys into the repo-server pod. But when I try to create the app I get: 

```
FATA[0001] rpc error: code = InvalidArgument desc = application spec is invalid: InvalidSpecError: Unable to get app details: rpc error: code = Unknown desc = `kustomize build /tmp/${repo_name} --enable_alpha_plugins` failed exit status 1: Error: trouble decrypting file ./secret.enc.yaml: Error getting data key: 0 successful groups required, got 0 
```
When I run this command `kustomize build /tmp/${repo_name} --enable_alpha_plugins` from within the pod, it works. 

Is this possible? What am I doing wrong?

**Comment by devstein** [comment]
Hi @HumairAK 

At a glance, this seems like it could be a permission issue. How are you mounting and importing the GPG private keys? What user are you when you run that command from within the pod? 

This doesn't appear to an issue with the plugin, but if you can share your kustomize patch I'm happy to try help debug!

**Comment by HumairAK** [comment]
Hey @devstein ! 
The patch is the same as the one here [https://github.com/viaduct-ai/kustomize-sops#ksops-repo-sever-patch](url). 

My workflow to import the keys is: 
```
$ pod=$(kubectl get pods | grep repo-server | awk 'NR==1{print $1}')
$ gpg --export-secret-keys "SOPS Functional Tests Key 1" > ${path_to_key}/private.asc
$ kubectl cp ${path_to_key}/private.asc ${pod}:/home/argocd
$ kubectl exec -it ${pod} -- /bin/bash

default@argocd-repo-server $ gpg --import ~/private.asc
```
I should mention that I'm running Argocd on Openshift, which, if you are unfamiliar, is built on top of kubernetes (so kubectl works as usual). I don't _think_ it should make much difference though (but if it works for you on kubernetes native, then I guess that would suggest otherwise).

```
default@argocd-repo-server $ id
uid=1000060000(default) gid=0(root) groups=0(root),1000060000
```

I think you might be right in that the issue isn't with the plugin. My question was, I suppose, more about _how_ I may use the plugin in this way, if possible of course.

Thanks for your help!

**Comment by devstein** [comment]
Thanks for the detailed response @HumairAK ! 

I still think this is a permission issue. GPG is strict about what users have access to which keys. When you run that workflow to import the key, you are making the key available to the `root` user, but Argo CD is running as the `argocd` user. You can see [full Argo CD Dockerfile here](https://hub.docker.com/r/argoproj/argocd/dockerfile). Two approaches come to mind:

1. Copy the PGP key into your custom `repo-server`, as the **argocd** user import the PGP key, then delete the copied key
2. Use a [postStart](https://kubernetes.io/docs/tasks/configure-pod-container/attach-handler-lifecycle-event/) script on your `repo-server` deployment that imports the key from a mount K8s secret

Let me know if either of these approaches work! If they don't, I encourage you to ask in the Argo CD slack about the best way to make PGP keys available to Argo CD. 

Once the key is available to the `argocd` user, KSOPS will work as expected.

**Comment by HumairAK** [comment]
Okay figured it out - I had to add the following env variable to the container spec in the repo-server patch: 
```
env:
    - name: GNUPGHOME
      value: /home/argocd/.gnupg
```

**Comment by james-callahan** [comment]
Does anyone have an demo of doing this?

**Comment by devstein** [comment]
Hi @james-callahan 👋 

What do you mean by demo?

**Comment by james-callahan** [comment]
> What do you mean by demo?

I got one working for myself: https://github.com/james-callahan/example-gitops
