### ISSUE TITLE
NewGenArgs arguments failing

### ISSUE THREAD

**Issue by halilkaya** [viaduct-ai/kustomize-sops#29]
Hi,

I guess after the latest changes, when I try to install ksops with the command below, I get the error.

```bash
$ go get -u github.com/viaduct-ai/kustomize-sops
...
# github.com/viaduct-ai/kustomize-sops
go/pkg/mod/github.com/viaduct-ai/kustomize-sops@v0.0.0-20200405180615-a3e1ac600551/ksops.go:102:32: too many arguments in call to types.NewGenArgs
	have (*types.GeneratorArgs, *types.GeneratorOptions)
	want (*types.GeneratorArgs)
```

I have also added a comment into the related commit:
https://github.com/viaduct-ai/kustomize-sops/commit/61ce22fb412f910250be5cb59099131ab68097ee#r39118374

Thanks,
Halil

**Comment by halilkaya** [comment]
It might be caused by my Go version. Could you please also add the required Go version in README?

**Comment by halilkaya** [comment]
Yes, the problem is about the Go version. I was using 1.14. When I use 1.13, it still fails but when it successes when specifying the 1.13 branch like:

```bash
go get -u github.com/viaduct-ai/kustomize-sops@go-1.13
```

**Comment by halilkaya** [comment]
However, it still fails when installing with make: :(

```bash
$ make install
go build -buildmode plugin -o "ksops.so"
# github.com/viaduct-ai/kustomize-sops
./ksops.go:102:32: too many arguments in call to types.NewGenArgs
	have (*types.GeneratorArgs, *types.GeneratorOptions)
	want (*types.GeneratorArgs)
make: *** [build-plugin] Error 2```

**Comment by devstein** [comment]
Hi @halilkaya !

Thanks for making an issue. I'm aware of this issue, we currently pin ksops to the latest `kustomize`, but the Go build for the latest kustomize version (v3.5.5) is broken. 

I'll make a PR to pin `make kustomize` to install a compatible version (v3.5.4) while we wait on a response from the `kustomize` team

Related issues for tracking:

https://github.com/viaduct-ai/kustomize-sops/pull/28
https://github.com/kubernetes-sigs/kustomize/issues/2462

**Comment by halilkaya** [comment]
Excellent! Thanks.

**Comment by devstein** [comment]
@halilkaya `master` branch should now be fixed
