### ISSUE TITLE
Doc tip

### ISSUE THREAD

**Issue by qcastel** [viaduct-ai/kustomize-sops#37]
I struggle quite a bit to install ksops on mac, mainly because I ended up trying many different things.
The main issue is that I did installed goland and kustomize via brew, which doesn't setup the GOPATH but more importantly, adding the GOPATH into PATH.

Therefore the install of kustomize didn't work and even if I first did try to compile kustomize directly (via their installation instructions), it didn't work for me.

So really the tips would be to make sure the mac user got their goland properly setup.
For that, add in bashrc or zshrc:

```
export GOPATH=/Users/$USER/go
export PATH=$GOPATH/bin:$PATH
```

A bit of a shame that brew doesn't do that properly, that would have avoid me some pain.

**Comment by devstein** [comment]
@qcastel Thanks for making an issue! I added a general section for verifying the installation of the example's requirements

**Comment by qcastel** [comment]
No worries!
Just looked your PR and I did verify my 'go env' a few times.
I first tried by setting up the GOPATH but that wasn't enough. The main things was to make sure in mac os, the GOPATH was also in the PATH.

You may say it's particular to my setup and you may be right. Although I just used brew and as I actually don't develop in GO, so far, I haven't had the need to compile Golang apps.
Anyway just saying that I bet it's a miss installed in brew of GO and as you rely on the fact that the GOPATH is part of the default PATH, you may want to make sure people have `export PATH=$GOPATH/bin:$PATH`
