### ISSUE TITLE
use goreleaser action to add ksops to github releases

### ISSUE THREAD

**Issue by jetersen** [viaduct-ai/kustomize-sops#43]
Instead of needing us to build ksops manually, would be nice if github actions had ksops built for us.

https://github.com/goreleaser/goreleaser-action

**Comment by devstein** [comment]
@jetersen Thanks for making an issue! This is a great suggestion, but it looks like [goreleaser doesn't/can't support Go plugins](https://github.com/goreleaser/goreleaser/issues/662), so we can't automate the `ksops` build for releases 😞 

Closing this, for now, feel free to reopen and if you know how to make it his work
