### ISSUE TITLE
Make Dockerfile available

### ISSUE THREAD

**Issue by clelange** [viaduct-ai/kustomize-sops#50]
Hey,

Thanks for making kustomize-sops openly available!

I'm looking into using KSOPS with Argo CD, but I need to patch SOPS to make it work with our OpenStack installation (in particular Barbican). Would it be possible that you made available the Dockerfile that you use to build the images on [docker hub](https://hub.docker.com/r/viaductoss/ksops/tags), e.g. add them to this repository?

That would be much appreciated!

**Comment by devstein** [comment]
@clelange Thanks for making an issue! Happy to do so.

**Comment by clelange** [comment]
Awesome, that was fast, thanks a lot!
Would you be interested in getting the size of this image down, e.g. via a multi-stage build? I could look into this at the beginning of August.

**Comment by devstein** [comment]
@clelange Great idea! Please feel free to contribute
