### ISSUE TITLE
Rebuild with kustomize 3.8.1

### ISSUE THREAD

**Issue by daurnimator** [viaduct-ai/kustomize-sops#53]
https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv3.8.1

> 
> This release purports to fix an issue arising from the switchover.
> 
> This release includes allowing empty lists in resources to be
> explicitly declared and retained as such.
> 
> So YAML like
> 
>   someList: []
> 
> won't be dropped in the course of transformation or formatting, as may happen to other empty fields.
> 
> Present but declaratively empty list (array) fields are handy as documentation and as
> targets for array extension under the fine print of rfc6902.
> 
> It's likely going to be important to allow patches to add entries to list fields that are completely missing (creating such fields in the process, as long as openapi type declarations are respected), but that's a different issue.

**Comment by devstein** [comment]
@daurnimator the `master` branch is already [built with v3.8.1](https://github.com/viaduct-ai/kustomize-sops/blob/master/scripts/install-kustomize.sh#L8), but I will publish a new docker image with it as well
