### ISSUE TITLE
Rewrite as external plugin?

### ISSUE THREAD

**Issue by daurnimator** [viaduct-ai/kustomize-sops#54]
Trying to keep up with go plugin compatibility isn't easy. It also means that we need releases of this plugin to update kustomize.

Should this kustomize-sops get rewritten as an [`execPlugin`](https://kubernetes-sigs.github.io/kustomize/guides/plugins/execpluginguidedexample/)?

**Comment by devstein** [comment]
@daurnimator I'll look into this. At a glance, it looks like we can support both the existing Go plugin pattern and an exec plugin pattern, so it can be left to user preference.

**Comment by devstein** [comment]
@daurnimator I added support for using KSOPS as an exec plugin in the latest release. Try it out and let me know if you run into any issues!

**Comment by daurnimator** [comment]
Awesome! just deployed it and works great.

Would you consider creating a docker image that contains *just* the ksops binary?

**Comment by devstein** [comment]
@daurnimator Yes that's definitely doable. What is your use-case for it?

**Comment by daurnimator** [comment]
> @daurnimator Yes that's definitely doable. What is your use-case for it?

https://github.com/hashbang/gitops/commit/e85956f43ed54b85af29867c5047b18abb627d46
