### ISSUE TITLE
Problem with building after vbom.ml/util was moved.

### ISSUE THREAD

**Issue by martinpovolny** [viaduct-ai/kustomize-sops#60]
I am having an issue building the project:
```
- [~/go/src/github.com/viaduct-ai/kustomize-sops] (master)$ make kustomize
./scripts/install-kustomize.sh
Installing kustomize...
go: downloading sigs.k8s.io/kustomize/kustomize/v3 v3.8.2
go get: sigs.k8s.io/kustomize/kustomize/v3@v3.8.2 requires
	sigs.k8s.io/kustomize/cmd/config@v0.6.0 requires
	k8s.io/kubectl@v0.0.0-20191219154910-1528d4eea6dd requires
	vbom.ml/util@v0.0.0-20160121211510-db5cfe13f5cc: unrecognized import path "vbom.ml/util": https fetch: Get "https://vbom.ml/util?go-get=1": dial tcp: lookup vbom.ml on 127.0.0.1:53: no such host
make: *** [Makefile:22: kustomize] Error 1

```

Seems the problem is fixed in upstream kubernetes:
https://github.com/kubernetes/kubernetes/pull/94451/files

Is this fixable by creating some dependency override? (not sure it that is possible, I am new to Go). Or do I have to report this in kustomize?

Thx!

**Comment by martinpovolny** [comment]
adding
`replace vbom.ml/util => github.com/fvbommel/sortorder v1.0.1` to `go.mod` helped get over this

**Comment by devstein** [comment]
@martinpovolny Thanks for making an issue and posting the solution 😄
