### ISSUE TITLE
plugin was built with a different version of package internal/cpu

### ISSUE THREAD

**Issue by triThirty** [viaduct-ai/kustomize-sops#66]
When I run `kustomize build --enable_alpha_plugins --load_restrictor=LoadRestrictionsNone`, it prompts `Error: loading generator plugins: plugin /Users/root/.config/kustomize/plugin/viaduct.ai/v1/ksops/ksops.so fails to load: plugin.Open("/Users/root/.config/kustomize/plugin/viaduct.ai/v1/ksops/ksops"): plugin was built with a different version of package internal/cpu`

- kustomize version : `{Version:3.8.1 GitCommit:0b359d0ef0272e6545eda0e99aacd63aef99c4d0 BuildDate:2020-07-16T05:11:04+01:00 GoOs:darwin GoArch:amd64}`

- ksops version: `kustomize-sops-2.1.3`

- go version: `go version go1.15.2 darwin/amd64`

I install ksops step by step according to READ.me
And I am not familiar with golang, so anyone can help me ?

**Comment by devstein** [comment]
@triThirty Thanks for making an issue. It looks like you didn't install `kustomize` correctly. Can you run `make kustomize` while in the ksops repo?

If successful, your `kustomize version` output should look like

```bash
{Version:v3.8.4+ksops.bc054bf4834a8bf1041b9919a0c4f14696d20876 GitCommit:v3@v3.8.4 BuildDate:2020-09-21T14:13:03Z GoOs:darwin GoArch:amd64}
```
