### ISSUE TITLE
Publish images to quay or another repo

### ISSUE THREAD

**Issue by HumairAK** [viaduct-ai/kustomize-sops#86]
With docker's new rate-limiting policies, we're seeing more organizations offer non docker alternatives to source their images. 

ArgoCD is also doing this see [here](https://github.com/argoproj/argo-cd/pull/5226) for more info. In the same vein, could we also get another non-docker alternative for the ksops builder image?

**Comment by devstein** [comment]
@HumairAK Great idea, I'll tackle this in the coming weeks.

**Comment by HumairAK** [comment]
Thanks @devstein !

**Comment by devstein** [comment]
Published to [Quay.io](https://quay.io/repository/viaductoss/ksops?tab=info) in the latest release!
