### ISSUE TITLE
`install-ksops-archive.sh` doesn't work; `make install-exec-only` does

### ISSUE THREAD

**Issue by mgoodness** [viaduct-ai/kustomize-sops#94]
Trying to install the KSOPS exec plugin for kustomize v4.0.4. When I run `kustomize build --enable-alpha-plugins ...` after installing via `scripts/install-ksops-archive.sh`, I get

```shell
Error: loading generator plugins: expected file with Go object code at: /Users/michael.goodness/.config/kustomize/plugin/viaduct.ai/v1/ksops-exec/ksops-exec.so
```

But the same command after installing via `make install-exec-only` (from `master`) works perfectly.

Help?

**Comment by devstein** [comment]
@mgoodness Have you previously installed the KSOPS Go plugin? That error code usually indicates there is both a KSOPS Go and Exec plugin in the same directory. The `scripts/install-ksops-archive.sh` doesn't clean the KSOPS folders for you, but `make install-exec-only` does

**Comment by mgoodness** [comment]
I'd tried removing the plugin directory altogether between attempts, but just ran `make clean` for good measure. Same result, I'm afraid.

**Comment by mgoodness** [comment]
Eureka! The problem is that `scripts/install-ksops-archive.sh` installs the ksops-exec plugin as `$XDG_CONFIG_HOME/kustomize/plugin/viaduct.ai/v1/ksops-exec/ksops` when it should be `.../ksops-exec`. PR incoming.
